classDiagram

Food <|-- RegularFood
Food <|-- FastFood
Food <|-- Baverage
Food <|-- Dessert

    class Food{
    
    }

    class RegularFood{
    
    }

    class FastFood{
    
    }

    class Baverage{
    
    }

    class Dessert{
    
    }

    class Order